---
title: "Projects"
author: "ahah"
date: '2021 11 30 '
output: html_document
---

## 데이터 불러오기 및 라이브러리 불러오기
```{r}
library(ggplot2)
library(dplyr)

# 서울 구 각각의 면적 데이터 불러오기 
seoul_gu_area <-read.csv('seoul_gu_area.csv')
seoul_gu_area
# 서울 구 각각의 인구 데이터 불러오기
seoul_gu_population <- read.csv('seoul_population.csv')
seoul_gu_population

# 1 ~ 12월 각각의 시간대별 배출 데이터 불러오기
hour_2020_01 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_01월_시간대별_종합배출내역.csv')
hour_2020_02 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_02월_시간대별_종합배출내역.csv')
hour_2020_03 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_03월_시간대별_종합배출내역.csv')
hour_2020_04 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_04월_시간대별_종합배출내역.csv')
hour_2020_05 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_05월_시간대별_종합배출내역.csv')
hour_2020_06 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_06월_시간대별_종합배출내역.csv')
hour_2020_07 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_07월_시간대별_종합배출내역.csv')
hour_2020_08 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_08월_시간대별_종합배출내역.csv')
hour_2020_09 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_09월_시간대별_종합배출내역.csv')
hour_2020_10 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_10월_시간대별_종합배출내역.csv')
hour_2020_11 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_11월_시간대별_종합배출내역.csv')
hour_2020_12 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_시간대별\\2020년_12월_시간대별_종합배출내역.csv')

# 1 ~ 12월 각각의 요일별 배출 데이터 불러오기

day_2020_01 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_01월_요일별_종합배출내역.csv')
day_2020_02 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_02월_요일별_종합배출내역.csv')
day_2020_03 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_03월_요일별_종합배출내역.csv')
day_2020_04 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_04월_요일별_종합배출내역.csv')
day_2020_05 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_05월_요일별_종합배출내역.csv')
day_2020_06 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_06월_요일별_종합배출내역.csv')
day_2020_07 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_07월_요일별_종합배출내역.csv')
day_2020_08 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_08월_요일별_종합배출내역.csv')
day_2020_09 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_09월_요일별_종합배출내역.csv')
day_2020_10 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_10월_요일별_종합배출내역.csv')
day_2020_11 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_11월_요일별_종합배출내역.csv')
day_2020_12 <- read.csv('@한국환경공단_RFID기반 음식물쓰레기 배출정보 20년 시간별, 일별, 요일별, 월별\\2020년_요일별\\2020년_12월_요일별_종합배출내역.csv')
```

# 1~12월 시간대, 요일별 데이터 하나의 데이터프레임으로 합치기 및 ton 단위 변수 추가
```{r}
hour_2020 <- bind_rows(hour_2020_01,hour_2020_02,hour_2020_03,hour_2020_04,hour_2020_05,hour_2020_06,hour_2020_07,hour_2020_08,hour_2020_09,hour_2020_10,hour_2020_11,hour_2020_12)

day_2020 <- bind_rows(day_2020_01, day_2020_02, day_2020_03, day_2020_04, day_2020_05, day_2020_06, day_2020_07, day_2020_08, day_2020_09, day_2020_10, day_2020_11, day_2020_12)

hour_2020$배출월 <- as.factor(hour_2020$배출월)

# 배출량 그램 단위는 숫자가 너무 커서 ton 단위로 바꿔주겠습니다!
hour_2020 <- hour_2020 %>% mutate(배출량.ton. = 배출량.g. / 1000000)
day_2020 <- day_2020 %>% mutate(일평균배출량.ton. = 일평균배출량.g. / 1000000)
```

# 시각화 작업하기 (시간대별 데이터)
```{r}
# 선 그래프로 시각화하기 1~12월 모두 아침 8~9시, 저녁 19~21시에 배출이 많음을 알 수 있다.
ggplot(data=hour_2020, aes(x=배출시간.시., y=배출량.ton., col=배출월)) + geom_line()

# 박스 그래프로 시각화하기 (월별 배출량) # 대체로 6~8월 여름, 11~12월 연말에 배출량이 많고, 1~4월 연초에는 배출량이 적음을 알 수 있다.
ggplot(data=hour_2020, aes(x=배출월, y=배출량.ton., fill=배출월)) + geom_col()

```

# 시각화 작업하기 (요일별 데이터)
```{r}
# 박스 그래프로 시각화하기 (요일별 배출량) 
# 음식물 쓰레기 배출량이 일요일에 가장 많고, 그 다음으로 월요일, 화~토요일에는 비슷하게 배출하는 것을 알 수 있다.
ggplot(data=day_2020, aes(x=요일, y=일평균배출량.ton., fill=요일)) + geom_boxplot()+scale_x_discrete(limits=c("월","화","수","목","금","토","일"))
```


